import type { Metadata } from "next";
import { Providers } from "../providers";
import "../../styels/global.css";

import Header from "@/components/home/Header";
import Footer from "@/components/footer/MainFooter";
export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/Chat-GPT-Image-Apr-24-2025-02-07-44-PM-removebg-preview%20(2).webp",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased  font-poppins ">
        <Providers>
          <div className="flex flex-col min-h-screen  md:max-w-7xl mx-auto">
            <Header />

            <main className=" bg-gray-100">
              {children}

              <Footer />
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
