import type { Metadata } from "next";
import { Providers } from "../providers";
import "../../styels/global.css"
import AdminShell from "@/components/admin/AdminSidebar";


export const metadata: Metadata = {
  title: "Admin Dashboard",
  icons: {
    icon: "/assets/Chat-GPT-Image-Apr-24-2025-02-07-44-PM-removebg-preview (2).webp",
  },
  keywords: ["Admin", "Dashboard", "Next.js"],
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased font-poppins">
        <Providers>
          {/* Wrap children inside the AdminShell */}
          <AdminShell>{children}</AdminShell>
        </Providers>
      </body>
    </html>
  );
}
